// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtNxcTTljrMmTx3W_Srv0Na0sBeCUDkxI',
    appId: '1:29693013811:web:2cfc9743a521185aba5846',
    messagingSenderId: '29693013811',
    projectId: 'animal-tracking-01',
    authDomain: 'animal-tracking-01.firebaseapp.com',
    databaseURL: 'https://animal-tracking-01-default-rtdb.firebaseio.com',
    storageBucket: 'animal-tracking-01.appspot.com',
    measurementId: 'G-7MQ80W5KXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7LVwn6f3_logqpsAo-49RZrzKIP4g8Go',
    appId: '1:29693013811:android:de7867eb27aa8b48ba5846',
    messagingSenderId: '29693013811',
    projectId: 'animal-tracking-01',
    databaseURL: 'https://animal-tracking-01-default-rtdb.firebaseio.com',
    storageBucket: 'animal-tracking-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtTwpJr52B415_DQtG3JEco3iO7HBLblc',
    appId: '1:29693013811:ios:23d00a2cecfd550fba5846',
    messagingSenderId: '29693013811',
    projectId: 'animal-tracking-01',
    databaseURL: 'https://animal-tracking-01-default-rtdb.firebaseio.com',
    storageBucket: 'animal-tracking-01.appspot.com',
    iosBundleId: 'com.example.patrolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtTwpJr52B415_DQtG3JEco3iO7HBLblc',
    appId: '1:29693013811:ios:23d00a2cecfd550fba5846',
    messagingSenderId: '29693013811',
    projectId: 'animal-tracking-01',
    databaseURL: 'https://animal-tracking-01-default-rtdb.firebaseio.com',
    storageBucket: 'animal-tracking-01.appspot.com',
    iosBundleId: 'com.example.patrolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtNxcTTljrMmTx3W_Srv0Na0sBeCUDkxI',
    appId: '1:29693013811:web:a95521d72324d9b7ba5846',
    messagingSenderId: '29693013811',
    projectId: 'animal-tracking-01',
    authDomain: 'animal-tracking-01.firebaseapp.com',
    databaseURL: 'https://animal-tracking-01-default-rtdb.firebaseio.com',
    storageBucket: 'animal-tracking-01.appspot.com',
    measurementId: 'G-3G6RVM53QG',
  );
}
